# Default values for elk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kibana:
  env:
    ELASTICSEARCH_URL: http://efk-elasticsearch-client:9200
  resources: 
      limits:
        cpu: "2"
        memory: 8192Mi
      requests:
        cpu: 100m
        memory: 300Mi
  dashboardImport:
    timeout: 60
    xpackauth:
      enabled: true
      username: myuser
      password: mypass
    dashboards: 
        k8s: https://raw.githubusercontent.com/monotek/kibana-dashboards/master/k8s-fluentd-elasticsearch.json

  plugins:
    # set to true to enable plugins installation
    enabled: true
    # set to true to remove all kibana plugins before installation
    reset: true
    # Use <plugin_name,version,url> to add/upgrade plugin
    values:
      # - elastalert-kibana-plugin,1.0.1,https://github.com/bitsensor/elastalert-kibana-plugin/releases/download/1.0.1/elastalert-kibana-plugin-1.0.1-6.4.2.zip
        - curator,1.0.0,https://github.com/suntekma/Charts/raw/master/elastic-stack/charts/kibana/plugin/curator-1.0.0.zip
        - X-Pack,6.2.4,https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-6.2.4.zip
      # - logtrail,0.1.30,https://github.com/sivasamyk/logtrail/releases/download/v0.1.30/logtrail-6.4.2-0.1.30.zip
      # - other_plugin      
logstash:
  enabled: false
  # elasticsearch:
  #   host: elastic-stack-elasticsearch-client

filebeat:
  enabled: false
  # config:
  #   output.file.enabled: false
  #   output.logstash:
  #     hosts: ["elastic-stack-logstash:5044"]
  # indexTemplateLoad:
  #   - elastic-stack-elasticsearch-client:9200

fluentd:
  enabled: false

fluent-bit:
  enabled: true
  backend:
    type: es
    es:
      host: efk-elasticsearch-client
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  parsers:
    enabled: true
    ## List the respective parsers in key: value format per entry
    ## Regex required fields are name and regex. JSON required field
    ## is name.
    regex:
        - name: nginx
          regex:  '^(?<host>[^ ]*) - \[(?<real_ip>)[^ ]*\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)'
          timeKey: time
          timeFormat: "%d/%b/%Y:%H:%M:%S %z"
    json: []
  # If true, enable the use of monitoring for a pod annotation of
  # fluentbit.io/exclude: true. If present, discard logs from that pod.
  enableExclude: true
  # If true, enable the use of monitoring for a pod annotation of
  # fluentbit.io/parser: parser_name. parser_name must be the name
  # of a parser contained within parsers.conf
  enableParser: true

fluentd-elasticsearch:
  enabled: false

nginx-ldapauth-proxy:
  enabled: false
  # Example config to get it working with ELK. Adjust as you need to.
  proxy:
    port: 5601
    # This is the internal hostname for the kibana service
    host: "efk-kibana"
    authName: "ELK:Infrastructure:LDAP"
    ldapHost: "10.1.37.133"
    ldapDN: "DC=BUYABS,DC=CORP"
    ldapFilter: "objectClass=organizationalPerson"
    ldapBindDN: "CN=IT LDAP Query Service Account,OU=ServiceAccounts,OU=ITIN,OU=Special Accounts,DC=buyabs,DC=corp"
    requires:
      - name: "ELK-USER"
        filter: "CN=Kubernetes,OU=Kubernetes,OU=CN,DC=buyabs,DC=corp"
  ingress:
    enabled: true
    hosts:
      - "e9k8s-efk.newegg.org"
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - hosts:
        - e9k8s-efk.newegg.org
        secretName: neweggorg-tls
  secrets:
    ldapBindPassword: "870+eeBgA[-JR01~xB*l1nZ*"

elasticsearch-curator:
  enabled: false
  config:
    elasticsearch:
      hosts:
        - efk-elasticsearch-client
      port: 9200

elasticsearch-exporter:
  enabled: true

elasticsearch:
  client:
    serviceType: NodePort
  master:
    persistence:
      size: "50Gi"
    resources:
     limits:
        cpu: "2"
        memory: "4096Mi"
     requests:
        cpu: "25m"
        memory: "512Mi"
  data:
    persistence:
      size: "500Gi"
    resources:
      limits:
        cpu: "8"
        memory: "4096Mi"
      requests:
        cpu: "25m"
        memory: "1536Mi"
  cluster:
    xpackEnable: true
